table 'S/Conto (sco) - Ricezioni'
	lineageTag: 8e33063d-8b7e-419f-8a71-bce24bd59122

	column codice_fornitore
		dataType: int64
		formatString: 0
		lineageTag: eb5cb9c6-fd36-458f-9bec-95c072f0c1c1
		summarizeBy: none
		sourceColumn: codice_fornitore

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Descrizione fornitore'
		dataType: string
		lineageTag: 74c02252-5900-4512-913e-8ccd3a8e5e97
		summarizeBy: none
		sourceColumn: Descrizione fornitore

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'S/Conto (sco) - Ricezioni' = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "SELECT * FROM sco"),
				    #"Rimosse altre colonne" = Table.SelectColumns(Origine,{"sc_cod_s_conto", "sc_descr"}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse altre colonne",{{"sc_cod_s_conto", "codice_fornitore"}, {"sc_descr", "Descrizione fornitore"}})
				in
				    #"Rinominate colonne"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

