table 'S/Conto (sco) - Ricezioni Galileo'
	lineageTag: f7472cb5-edc1-4e70-9659-cd0df5161a83

	column codice_fornitore
		dataType: int64
		formatString: 0
		lineageTag: 51d58dc0-44e3-48ae-87ca-8c96cdf40ef0
		summarizeBy: sum
		sourceColumn: codice_fornitore

		annotation SummarizationSetBy = Automatic

	column 'Descrizione fornitore'
		dataType: string
		lineageTag: 97ad5eb2-621a-4192-bf29-379d23a70517
		summarizeBy: none
		sourceColumn: Descrizione fornitore

		annotation SummarizationSetBy = Automatic

	column 'Codice fornitore Galileo'
		dataType: int64
		formatString: 0
		lineageTag: b96c4ed6-c57a-4e45-948e-e7ad8cee63c8
		summarizeBy: sum
		sourceColumn: Codice fornitore Galileo

		annotation SummarizationSetBy = Automatic

	partition 'S/Conto (sco) - Ricezioni Galileo' = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "SELECT * FROM sco"),
				    #"Rimosse altre colonne" = Table.SelectColumns(Origine,{"sc_cod_s_conto", "sc_descr", "sc_cod_precedente"}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse altre colonne",{{"sc_cod_s_conto", "codice_fornitore"}, {"sc_descr", "Descrizione fornitore"}, {"sc_cod_precedente", "Codice fornitore Galileo"}}),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Rinominate colonne",{{"Codice fornitore Galileo", Int64.Type}})
				in
				    #"Modificato tipo"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

